build:
  version: "1.0"

accounts:
  message: "Welcome to SecureBank accounts related default APIs"
  contactDetails:
    name: "Alhagie - Product Owner"
    email: "default@abcham.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
  environment:
    name: "default"