server:
  port: 8071
spring:
  application:
    name: master-ms-sb-config-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#          search-locations: file:///Users/Document/config